#   Un pequeño esquema de makefile

grafo.o: grafo.c grafo.h
	gcc -c grafo.c

fuenteAuxiliar/cola.o: fuenteAuxiliar/cola.c fuenteAuxiliar/cola.h
	gcc -c fuenteAuxiliar/cola.c -o fuenteAuxiliar/cola.o

clean:
	rm -rfv *.o */*.o
